[[query]]
name="All Systems"
description="Query all systems"
query="""SELECT ?sys WHERE {
    ?sys rdf:type/rdfs:subClassOf* s223:System .
}"""

[[query]]
name="Temperature Sensors"
description="find sensors that measure temperature"
query="""SELECT ?sensor ?location WHERE {
    ?sensor rdf:type/rdfs:subClassOf* s223:Sensor .
    ?sensor s223:observesProperty ?property .
    ?property qudt:hasQuantityKind quantitykind:Temperature .
    ?sensor s223:hasMeasurementLocation ?location
}"""

[[query]]
name="Systems Serving Zones"
description="find systems that serve zones"
query="""SELECT ?zone ?system WHERE {
	?zone rdf:type/rdfs:subClassOf* s223:Zone .
    ?system rdf:type/rdfs:subClassOf* s223:System ;
            s223:servesZone ?zone .
}"""

[[query]]
name="Devices Serving Zones"
description="find devices that serve zones"
query="""SELECT DISTINCT ?zone ?system ?device WHERE {
	?zone rdf:type/rdfs:subClassOf* s223:Zone .
    ?system rdf:type/rdfs:subClassOf* s223:System ;
            s223:contains ?device ;
            s223:servesZone ?zone .
    ?device rdf:type/rdfs:subClassOf* s223:Device .
}"""
